# Generated by Django 6.0.5 on 2026-05-10 19:59
"""
Первая миграция для инициализации БД
"""
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Модель контрактов определяется в БД
    """
    initial = True

    dependencies = [
        ('ads', '0001_initial'),
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(null=True, upload_to='contracts/file')),
                ('date', models.DateField(auto_now_add=True)),
                ('duration', models.DurationField()),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.advert')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.profile')),
            ],
            options={
                'ordering': ['pk', 'name'],
            },
        ),
    ]
