# Generated by Django 6.0.5 on 2026-05-12 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='price',
            new_name='cost',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='profile',
        ),
    ]
