# Generated by Django 6.0.5 on 2026-05-12 20:35
"""
Переименование полей модели
"""
from django.db import migrations


class Migration(migrations.Migration):
    """
    Поле переименовано "price" на  "cost"
    """
    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='price',
            new_name='cost',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='profile',
        ),
    ]
