# Generated by Django 6.0.5 on 2026-05-12 21:22
"""
Изменение полей
"""
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Изменено свойство поля "услуги"
    """
    dependencies = [
        ('contracts', '0002_rename_price_contract_cost_remove_contract_profile'),
        ('products', '0002_rename_price_product_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='products',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
