# Generated by Django 6.0.5 on 2026-05-16 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_alter_contract_products'),
        ('leads', '0004_rename_profile_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.lead', verbose_name='Лид'),
        ),
    ]
