# Generated by Django 6.0.5 on 2026-05-16 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_contract_lead'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='date',
            new_name='start_date',
        ),
    ]
