# Generated by Django 6.0.5 on 2026-05-20 17:24
"""Изменено значение поля """
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Добавлено blanc=True  полю "file"
    """
    dependencies = [
        ('contracts', '0005_rename_date_contract_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='contracts/file'),
        ),
    ]
