# Generated by Django 6.0.5 on 2026-05-10 19:59
"""
Первая миграции для инициализации моделей в БД
"""
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Создана модель услуг в БД
    """
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
