# Generated by Django 6.0.5 on 2026-05-11 16:25
"""
переименование поля
"""
from django.db import migrations


class Migration(migrations.Migration):
    """
    Поле изменено "price" на "cost"
    """
    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='cost',
        ),
    ]
