# Generated by Django 6.0.5 on 2026-05-16 22:06
"""
Обновление поля модели
"""

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Изменение атрибутов поля "due_date"
    """
    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2026, 5, 16, 22, 6, 35, 471302, tzinfo=datetime.timezone.utc)),
        ),
    ]
