# Generated by Django 6.0.5 on 2026-05-16 22:07
"""
Изменение поля модели
"""
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Изменение поля "due_date"
    """
    dependencies = [
        ('tasks', '0002_alter_tasks_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='due_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
