# Generated by Django 6.0.5 on 2026-05-12 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_alter_contract_products'),
        ('customers', '0001_initial'),
        ('leads', '0003_alter_profile_options_remove_profile_fullname_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ActiveProfile',
            new_name='Customer',
        ),
    ]
