# Generated by Django 6.0.5 on 2026-05-12 21:49
"""
Изменение  поля
"""
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Изменение атрибутов поля "profile"
    """
    dependencies = [
        ('contracts', '0003_alter_contract_products'),
        ('customers', '0002_rename_activeprofile_customer'),
        ('leads', '0003_alter_profile_options_remove_profile_fullname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='contract',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='contracts.contract'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='leads.profile'),
        ),
    ]
