# Generated by Django 6.0.5 on 2026-05-12 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_customer_contract_alter_customer_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='profile',
            new_name='lead',
        ),
    ]
