# Generated by Django 6.0.5 on 2026-05-16 12:47
"""
Изменение полей
"""
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Изменение атрибутов полей "lead" и "contract"
    """
    dependencies = [
        ('contracts', '0004_contract_lead'),
        ('customers', '0004_rename_profile_customer_lead'),
        ('leads', '0004_rename_profile_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='contract',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='customers', to='contracts.contract'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='customers', to='leads.lead'),
        ),
    ]
