# Generated by Django 6.0.5 on 2026-05-24 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0005_alter_customer_contract_alter_customer_lead"),
        ("leads", "0005_alter_lead_advert_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="lead",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="customers",
                to="leads.lead",
            ),
        ),
    ]
