# Generated by Django 6.0.5 on 2026-05-24 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0006_alter_contract_file"),
        ("customers", "0006_alter_customer_lead"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="contract",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="customers",
                to="contracts.contract",
            ),
        ),
    ]
