# Generated by Django 6.0.5 on 2026-05-10 19:59
"""
Создание модели потенциальных клиентов в БД
"""
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Первичная инициализация модели в БД
    """
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('advert_name', models.CharField(default='', max_length=250)),
            ],
            options={
                'ordering': ['pk', 'fullname'],
            },
        ),
    ]
