# Generated by Django 6.0.5 on 2026-05-12 20:03
"""
Изменение поля
"""
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Изменение атрибутов поля "advert_name"
    """
    dependencies = [
        ('ads', '0002_rename_price_advert_budget'),
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='advert_name',
            field=models.ForeignKey(default='without_adverting', on_delete=django.db.models.deletion.SET_DEFAULT, to='ads.advert'),
        ),
    ]
