# Generated by Django 6.0.5 on 2026-05-12 20:08
"""
Изменение модели потенциальных клиентов
"""
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Ввод новых полей в модель
    """
    dependencies = [
        ('leads', '0002_alter_profile_advert_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['pk', 'first_name']},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='fullname',
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
