# Generated by Django 6.0.5 on 2026-05-13 20:07
"""
Переименование поля
"""
from django.db import migrations


class Migration(migrations.Migration):
    """
    Поле "profile" изменено на "lead"
    """
    dependencies = [
        ('ads', '0002_rename_price_advert_budget'),
        ('customers', '0004_rename_profile_customer_lead'),
        ('leads', '0003_alter_profile_options_remove_profile_fullname_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Lead',
        ),
    ]
