# Generated by Django 6.0.5 on 2026-05-16 12:47
"""
Изменение поля
"""
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Изменены атрибуты поля "advert_name"
    """
    dependencies = [
        ('ads', '0002_rename_price_advert_budget'),
        ('leads', '0004_rename_profile_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='advert_name',
            field=models.ForeignKey(default='without_adverting', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='leads', to='ads.advert'),
        ),
    ]
