# Generated by Django 6.0.5 on 2026-05-24 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0002_rename_price_advert_budget"),
        ("leads", "0005_alter_lead_advert_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="advert_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="leads",
                to="ads.advert",
            ),
        ),
    ]
