# Generated by Django 6.0.5 on 2026-05-10 19:59
"""
Миграция для инициализации модели рекламной компании в базе данных
"""

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Первая инициализация (построение) модели в БД: определены поля
    и их значения.
    """

    initial = True

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Advert",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=250)),
                ("promotion_path", models.CharField(max_length=250)),
                ("price", models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ("products", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="products.product")),
            ],
            options={
                "ordering": ["pk", "name"],
            },
        ),
    ]
