# Generated by Django 6.0.5 on 2026-05-10 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advert',
            old_name='price',
            new_name='budget',
        ),
    ]
